# Generated by Django 5.2 on 2025-06-06 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0004_alter_post_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.CharField(choices=[('realtime', '@リアタイ実況'), ('special', '@特設会場'), ('create', '@創作総合'), ('unei', '@運営批判'), ('pc', '@ガジェ・PC'), ('meshi', '@自炊・飲食部'), ('midnight', '@深夜雑談部'), ('trip', '@旅行総合'), ('tech', '@技術'), ('rikei', '@理系部'), ('cat', '@猫・ペット'), ('prole', '@学業とお仕事'), ('st', '雑談したい'), ('bosyuu', 'フレンド募集'), ('lignistic', '@言語総合'), ('game', '@ゲーム'), ('kane', '@投資・経営'), ('politi', '@政治、法'), ('oversea', '@海外情勢'), ('r18', '@R18'), ('constitution', '@無法地帯'), ('asia', 'asianchaos'), ('other', '@その他'), ('are', '@例のアレ'), ('anything', 'nandemo')], default='other', max_length=20),
        ),
    ]
