# Generated by Django 5.2 on 2025-06-07 07:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('board', '0005_alter_post_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='category',
        ),
    ]
